Config:
  autoBackup:
    Enable: false
    time: 2000
  logPath: log\
  watchDog: true
  #请使用转义符号表示"."
  key:
    key: ''
    enable: false
  sql:
    db: ''
    url: ''
    port:
    user: ''
    passwd: ''
    queryString: ''
  web:
    port: